#!/bin/sh

# report text files with CRLF terminators (anywhere in the file)

# License: LGPLv2

find \( -type d -a \( -name '.git' -o -name '.svn' -o -name 'CVS' \)  \) -prune -o \
     \( -type f -print0 \) |
xargs -r0 file |
LANG=C grep -F "text, with CRLF" |
cut -d: -f1
