#!/bin/sh

# Display ENAME corresponding to number
# or all ENAMEs if no number specified.

[ $# -eq 1 ] && re="$1([^0-9]|$)"
echo "#include <errno.h>" |
cpp -dD -CC | #-CC available since GCC 3.3 (2003)
grep -E "^#define E[^ ]+ $re"
