#!/bin/sh

# Display ENAME corresponding to number
# or all ENAMEs if no number specified.

[ "$#" -ne "1" ] && re="[^ ]+\$" || re=$1\$
echo "#include <errno.h>" |
cpp -dD |
grep -E "#define E[^ ]+ $re"
