#!/bin/sh

# Display ENAME corresponding to number
# or all ENAMEs if no number specified.

if [ "$#" -ne "1" ]; then
    re="[^ ]+\$"
else
    re=$1\$
fi

echo "#include <errno.h>" |
cpp -dD |
grep -E "#define E[^ ]+ $re"
